# Generated by Django 3.2 on 2023-04-20 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20230420_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(help_text='Дайте оценку произведению.', validators=[django.core.validators.MinValueValidator(1, 'Минимум 1'), django.core.validators.MaxValueValidator(10, 'Максимум 10')], verbose_name='Оценка'),
        ),
    ]
